// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://plskhjrrwofdroicafnr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsc2toanJyd29mZHJvaWNhZm5yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM1OTI4ODcsImV4cCI6MjA1OTE2ODg4N30.lX-8Vx0xECgVRgpVtELFQUqcrU19KRwvvSR-_ObSZYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);